### ISSUE TITLE
CollapsableText doesn't support anchor elements

### ISSUE THREAD

**Issue by chrism6475** [appfolio/react-gears#1157]
**Problem**
The `CollapsableText` component currently only supports strings, as it uses string.substring() to trim the text. This limitation prevents the use of anchor elements within the text, making it impossible to display a shrunken description containing hyperlinks.

**Example**
Suppose we want to use the `CollapsableText` to display a block of text containing marketing campaign and hyperlinks to units:
<img width="1188" alt="Screenshot 2023-05-01 at 1 40 11 PM" src="https://user-images.githubusercontent.com/15149443/235508548-8efc6e0a-03c0-4543-82d7-7820dc510e63.png">

This is the result when that text is wrapped in `CollapsableText`:
<img width="728" alt="Screenshot 2023-05-01 at 1 41 46 PM" src="https://user-images.githubusercontent.com/15149443/235508759-d3d39a47-54f8-4c54-a648-9a2ddbc87693.png">

**Observed Result**
The Collapsable Text component doesn't handle text containing an anchor tag at all and may through an error due to a call to [string.substring()](https://github.com/appfolio/react-gears/blob/master/src/components/CollapsableText/CollapsableText.tsx#LL36C18-L36C63) on a react element.

**Desired Result**
`CollapsableText` should support anchor elements, allowing them to be displayed properly within the component. The component should be able to trim the text, including any tags, and correctly shrink the content with hyperlinks and other HTML elements.

**Comment by Brian-Holland** [comment]
This was completed by @JeremyRH
