### ISSUE TITLE
CurrencyInput deletes trailing decimal when deleting the last decimal digit

### ISSUE THREAD

**Issue by scottpchow23** [appfolio/react-gears#832]
![Kapture 2021-03-31 at 17 54 58](https://user-images.githubusercontent.com/15284810/113228677-3affa600-924a-11eb-9370-b3f6be5f7ab9.gif)

Steps to reproduce
- Input `123456.78{delete}{delete}`

Observed
- `123,456`

Desired
- `123,456.` (until we blur field)

Dev notes:
- Currently, this issue is being caused by the `guide: false` prop being set [here](https://github.com/appfolio/react-gears/blob/839a161a5fa536fa54a6c8e1b68db3d60d8ae7d0/src/components/CurrencyInput.tsx#L70).
- Unfortunately, `react-text-mask` is no longer maintained (as of 2017), so updating that would be difficult without an internal fork.
- Another possibility is this repo [here](https://github.com/cchanxzy/react-currency-input-field). It's much younger and suffers from some [small deletion issues](https://github.com/cchanxzy/react-currency-input-field/issues/153), but solves _this_ particular issue.

**Comment by phwebi** [comment]
Fixed in https://github.com/appfolio/react-gears/pull/842!
