### ISSUE TITLE
Request for mapping address values with custom names

### ISSUE THREAD

**Issue by joyjoy993** [appfolio/react-gears#834]
Hi, I realize that `AddressInput` has a prop `inputName` that allows us to map custom field names. It would be nice that we can map address values with custom field names as well.
In IM, our address model looks like this:
```
city: "sfdsx"
countryCode: "US"
postalCode: "11220"
state: "AR"
street1: "xxxx"
street2: ""
```
so every time when we pass or fetch the value from `AddressInput`, we need to do a conversion.
I'm wondering if we can have another prop something like `mapValuesWithCustomFields` to convert values here https://github.com/appfolio/react-gears/blob/master/src/components/AddressInput.js#L68
like
```
propsFor = (field) => {
	const value = mapValuesWithCustomFields ? this.props.value[this.nameFor(field)] : this.props.value[field];
	const defaultValue = mapValuesWithCustomFields ? this.props.defaultValue[this.nameFor(field)] : this.props.defaultValue[field];
	if (value !== undefined) {
	  return { value };
	}
	return { defaultValue };
}
```
and then we can pass
```
<AddressInput
	inputName={{
		address1: 'street1',
		address2: 'street2',
		state: 'state',
		postal: 'postalCode',
		countryCode: 'countryCode',
		city: 'city'
	}}
	mapValuesWithCustomFields={true}
	......
```
This would help us to simplify the logic a lot, I don't know what's the cost of this change from RG standpoint, if it's feasible, I'm happy to drop a PR to do this.
Thanks.

**Comment by phwebi** [comment]
@joyjoy993 I looked into this and it actually seems like a bug from the original feature to add custom names to the fields! I think we should automatically use the custom names if they're provided. Seems like an easy enough fix, so happy to tackle that this morning and pass it over for you to review if you don't mind. (Just to make sure it'll work for your use case)
